services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis
        restart: always

    backend:
        build:
            context: .
            dockerfile: ./Dockerfile.back.dev
            args:
                PORT: ${PORT}
        container_name: back
        restart: always
        env_file: ./back/.env
        working_dir: /app
        volumes:
            - ./back:/app
            - /app/node_modules
        environment:
            - API_URI=http://localhost:${PORT}
            - FRONT_URI=http://localhost:${FRONT_PORT}
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - db
            - redis

    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile.front.dev
            args:
                PORT: ${FRONT_PORT}
        container_name: front
        restart: always
        env_file: ./front/.env
        working_dir: /app
        command: npm run dev -- --host --port ${FRONT_PORT}
        volumes:
            - ./front:/app
            - /app/node_modules
            - ./back/app/types:/app/back/app/types:ro
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - PUBLIC_PORT=${FRONT_PORT}
            - PUBLIC_FRONT_URI=http://frontend:${FRONT_PORT}
            - PUBLIC_API_BASE_URI=http://backend:${PORT}
            - PUBLIC_API_REAL_URI=http://localhost:${PORT}
            - PUBLIC_GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
        ports:
            - '${FRONT_PORT}:${FRONT_PORT}'
        depends_on:
            - backend

    adminer:
        image: ghcr.io/shyim/adminerevo:latest
        container_name: adminer
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - db

volumes:
    postgres_data:
