export enum NotificationTypeEnum {
    STATUS_TRANSITION = 'status_transition',
    MANDATE_ASSIGNED = 'mandate_assigned',
    MANDATE_REVOKED = 'mandate_revoked',
    DELIVERABLE_UPLOADED = 'deliverable_uploaded',
    DELIVERABLE_EVALUATED = 'deliverable_evaluated',
    DEADLINE_APPROACHING = 'deadline_approaching',
    NONCONFORMITY_THRESHOLD = 'nonconformity_threshold',
    PROCEDURE_OPENED = 'procedure_opened',
    REVOCATION_VOTE_OPENED = 'revocation_vote_opened',
    COMMENT_ADDED = 'comment_added',
    CLARIFICATION_ADDED = 'clarification_added',
    CLARIFICATION_UPDATED = 'clarification_updated',
    CLARIFICATION_DELETED = 'clarification_deleted',
    EXCHANGE_SCHEDULED = 'exchange_scheduled',
}
