export enum NotificationTypeEnum {
    STATUS_TRANSITION = 'status_transition',
    MANDATE_ASSIGNED = 'mandate_assigned',
    MANDATE_REVOKED = 'mandate_revoked',
    DELIVERABLE_UPLOADED = 'deliverable_uploaded',
    DELIVERABLE_EVALUATED = 'deliverable_evaluated',
    DEADLINE_APPROACHING = 'deadline_approaching',
    NONCONFORMITY_THRESHOLD = 'nonconformity_threshold',
    PROCEDURE_OPENED = 'procedure_opened',
    REVOCATION_VOTE_OPENED = 'revocation_vote_opened',
    COMMENT_ADDED = 'comment_added',
    CLARIFICATION_ADDED = 'clarification_added',
    CLARIFICATION_UPDATED = 'clarification_updated',
    CLARIFICATION_DELETED = 'clarification_deleted',
    EXCHANGE_SCHEDULED = 'exchange_scheduled',
    CONTENT_REPORTED = 'content_reported',
    CONTENT_REPORT_REVIEWED = 'content_report_reviewed',
    CONTENT_HIDDEN = 'content_hidden',
    DEADLINE_REMINDER_48H = 'deadline_reminder_48h',
    DEADLINE_REMINDER_24H_INITIATOR = 'deadline_reminder_24h_initiator',
    WEEKLY_VOTE_DIGEST = 'weekly_vote_digest',
    VOTE_QUORUM_WARNING = 'vote_quorum_warning',
}
